# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f742f654505918a46151318065c415b7c027e8a79f867b0f6a74ec3d55ae87f2b6cbab6c55c9513791ef74720f2a7ed0e85dd00a9aefc83e6e8b1c69818bf673

test:
  secret_key_base: 2ee7e998843c4632ff35164821e044ee9a412f2356215e345c06f3d7a1c823e46124dcc60bae327b65cd410e160d73927cd8b316df670da0e73b70fb89b095a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
